-- CreateTable
CREATE TABLE "Spending" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "amount" REAL NOT NULL,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,
    "colocId" TEXT NOT NULL,
    CONSTRAINT "Spending_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Spending_colocId_fkey" FOREIGN KEY ("colocId") REFERENCES "Coloc" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
